








name: Run Scrapper - Udate data

on:
  schedule:
    - cron: '*/5 * * * *'

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/ossp_flaskapp    #생성할 이미지 명
  VERSION: ${{ github.sha }}
  NAME: ossprac_container    #생성할 컨테이너 명

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: commits
      run: 
        git config --local user.email kdgk9620@gmail.com
        git config --local user.name kimdonggeun111
        git add data.json
        git commit -m "Auto - Update data with Scraping" # 커밋 메세지
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'main'
        github_token: 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
