name: Run Scrapper - Udate data

on:
  schedule:
    - cron: '*/5 * * * *'


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./app/crawl temp
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Scraper
      run:
        python "DGU.py"
      working-directory: ${{ env.working-directory }}
        
    - name: commits
      run: 
        git config --global user.email "kdgk9620@gmail.com"
        git config --global user.name "kimdonggeun111"
        git add dgu_list.json
        git commit -m "update dgu_list"
        
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'main'
        github_token: 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
